apply after generate ni

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -9,7 +9,7 @@ on:
       action:
         description: 'Terraform action to perform (apply/destroy)'
         required: true
-        default: 'apply'
+        default: 'destroy'
         type: choice
         options:
           - apply
@@ -20,7 +20,7 @@ jobs:
     runs-on: ubuntu-latest
     
     env:
-      TF_ACTION: ${{ github.event.inputs.action || 'apply' }}
+      TF_ACTION: ${{ github.event.inputs.action || 'destroy' }}
 
     steps:
     - name: Checkout code
@@ -74,11 +74,23 @@ jobs:
       if: env.TF_ACTION == 'apply'
       run: bash scripts/generate_inventory.sh  
 
-    - name: Add SSH host to known_hosts
+    # - name: Add SSH host to known_hosts
+    #   if: env.TF_ACTION == 'apply'
+    #   run: |
+    #     ssh-keyscan -H $(awk '/master/ {print $1}' ansible/inventory.ini) >> ~/.ssh/known_hosts  
+    - name: Add SSH host(s) to known_hosts
       if: env.TF_ACTION == 'apply'
       run: |
-        ssh-keyscan -H $(awk '/master/ {print $1}' ansible/inventory.ini) >> ~/.ssh/known_hosts  
-     
+        HOSTS=$(awk '/ansible_host|^([0-9]{1,3}\.){3}[0-9]{1,3}/ {print $1}' ansible/inventory.ini)
+        if [ -z "$HOSTS" ]; then
+          echo "No hosts found in inventory.ini"
+          exit 1
+        fi
+
+        for host in $HOSTS; do
+          echo "Scanning $host"
+          ssh-keyscan -H "$host" >> ~/.ssh/known_hosts || echo "ssh-keyscan failed for $host"
+        done  
 
     - name: Test SSH to master
       if: env.TF_ACTION == 'apply'
